from .melody import MELODY
from .text import SENTENCE_TUPLE

PAGE_COUNT = len(SENTENCE_TUPLE)

LONG_BREATH_DURATION = 7  # seconds
SHORT_BREATH_DURATION = 4  # seconds

BREATH_COUNT_PER_LINE = 4
LINE_COUNT_PER_PAGE = 3

BREATH_COUNT_PER_PAGE = BREATH_COUNT_PER_LINE * LINE_COUNT_PER_PAGE

PAGE_DURATION = BREATH_COUNT_PER_LINE * LONG_BREATH_DURATION * LINE_COUNT_PER_PAGE

DURATION = PAGE_DURATION * PAGE_COUNT
DURATION_IN_MINUTES = DURATION / 60


MELODY_NOTE_COUNT = sum([len(m) for m in MELODY])

INTERNAL_BREATH_DURATION = 1

del MELODY, SENTENCE_TUPLE
