#!/usr/bin/env bash
echo "set sampling rate to 44100"
pw-metadata -n settings 0 clock.force-rate 44100
echo "set buffersize to 256"
pw-metadata -n settings 0 clock.force-quantum 256
echo "start performance mode"
performance-on
echo "start qjackctl"
qjackctl -s -a ./etc/qjackctl/102-production.xml &
./scripts/walkman
performance-off
