#!/usr/bin/env bash
function upload () {
    arduinoIndex=$1
    echo "Upload to arduino $arduinoIndex"
    arduino-cli upload --fqbn arduino:avr:uno --port /dev/ttyACM$arduinoIndex etc/arduino/aeolianHarp/aeolianHarp.ino
}


echo "Compile script"
arduino-cli compile --fqbn arduino:avr:uno etc/arduino/aeolianHarp/aeolianHarp.ino

upload 0
upload 1
upload 2
