#!/usr/bin/env bash
arduino-cli compile --fqbn arduino:avr:uno etc/arduino/aeolianHarp/aeolianHarp.ino
arduino-cli upload --fqbn arduino:avr:uno --port /dev/ttyACM0 etc/arduino/aeolianHarp/aeolianHarp.ino
