[configure]
name                    = "10.1"
logging_level           = "info"

[configure.audio]
audio                   = "jack"
midi                    = "jack"
sampling_rate           = 44100
buffer_size             = 512
channel_count           = 4

